# Generated by Django 5.1.2 on 2025-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
